name: Update all logos on push to main branch

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false
  push:
    branches:
      - main

jobs:
  list-repos:
    name: Get list of all Stepman.AI repositories
    runs-on: ubuntu-latest
    outputs: 
      repo_list: ${{ steps.get-repo-list.outputs.repos }}
    steps:
      - name: Check out .profile repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Check object (for debugging only)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Get list of all repositories in stepmanai organization.
        id: get-repo-list
        run: echo "repos=$(gh repo list stepmanai --visibility=public --json name --jq 'map(.name | ascii_downcase | select(contains(".github") | not)) | @json')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_KEY }}


  upload-logo:
    name: Upload logos to assets folder in repo
    runs-on: ubuntu-latest
    needs: [list-repos]
    strategy: 
      matrix: 
        repo: ${{ fromJSON(needs.list-repos.outputs.repo_list) }}
    steps:
      - name: Verifying list-repo job is successful
        run: echo "${{ matrix.repo }}"

      - name: Push logos to external repository
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ACTION_KEY }}
        with:
          source-files: 'profile/assets/logo/${{ matrix.repo }}/*'
          destination-branch: main
          destination-username: stepmanai
          destination-repository: ${{ matrix.repo }}
          destination-directory: 'assets/logo/'
          commit-email: ${{ github.actor_id }}+stepmanai@users.noreply.github.com
