name: Update all logos on push to main branch

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false
  push:
    branches:
      - main

jobs:
  upload-logos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out .profile repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Check object (for debugging only)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Get list of all repositories in stepmanai organization.
        run: echo "GITHUB_REPOS=$(gh repo list stepmanai --visibility=public --json name --jq 'map(.name | select(contains(".github") | not))')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_KEY }}

      - name: Test
        run: echo $GITHUB_REPOS

      # - name:
      #   run: ||
      #     git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/project target
      #     rm everything but the .git directory
      #     copy source\files target
      #     cd target
      #     git add .
      #     git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
      #     git push target master

      # - name: Push logos to all stepmanai repositories
      #   uses: derberg/manage-files-in-multiple-repositories@v2
      #   with:
      #     github_token: ${{ secrets.GH_ACTION_KEY }}
      #     patterns_to_include: 'profile/assets/logo/'
      #     patterns_to_ignore: '.github/workflows/update-logos-in-repos.yml'
      #     committer_username: ${{ github.actor }}
      #     committer_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
      #     commit_message: "Created ${{ github.event.repository.name }} project with update-logos-in-repos workflow from .github."
