name: Update all logos on push to main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Check out .profile repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Check object (for debugging only)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Push logos to all stepmanai repositories
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.GH_ACTION_KEY }}
          patterns_to_include: 'profile/assets/logo/*'
          patterns_to_ignore: '.github/workflows/update-logos-in-repos.yml'
          committer_username: ${{ github.actor }}
          committer_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          commit_message: "Created ${{ github.event.repository.name }} project with update-logos-in-repos workflow from .github."
